# Generated by Django 3.1.1 on 2021-02-02 22:47

import contact_page.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=150)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=256, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[contact_page.models.phonenumber])),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='h_office', to='contact_page.address')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=256, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[contact_page.models.phonenumber])),
                ('mailing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='v_office', to='contact_page.address')),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.TextField(default='Undecided')),
                ('fixed', models.BooleanField(default=False)),
                ('host', models.ManyToManyField(blank=True, related_name='meetings', to='contact_page.Host')),
                ('visitor', models.ManyToManyField(blank=True, related_name='meetings', to='contact_page.Visitor')),
            ],
        ),
    ]
