# Generated by Django 3.1.1 on 2021-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0002_meeting_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='Not set', max_length=256),
        ),
    ]
