# Generated by Django 3.1.1 on 2021-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0003_host_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='password',
        ),
        migrations.AddField(
            model_name='host',
            name='passwordhash',
            field=models.IntegerField(null=True),
        ),
    ]
