# Generated by Django 3.1.1 on 2021-02-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0004_auto_20210203_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='passwordhash',
        ),
    ]
