# Generated by Django 3.1.1 on 2021-02-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0005_remove_host_passwordhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
