# Generated by Django 3.1.1 on 2021-02-03 18:44

import contact_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0006_host_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='email_address',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[contact_page.models.phonenumber]),
        ),
    ]
