# Generated by Django 3.1.1 on 2021-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0007_auto_20210203_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='email_address',
            new_name='email',
        ),
    ]
