# Generated by Django 3.1.1 on 2021-02-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0009_remove_host_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='profile_completed',
        ),
    ]
