# Generated by Django 3.1.1 on 2021-02-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0010_remove_host_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mailing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='v_office', to='contact_page.address'),
        ),
    ]
