# Generated by Django 3.1.1 on 2021-02-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0011_auto_20210203_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mailing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='h_office', to='contact_page.address'),
        ),
    ]
