# Generated by Django 3.1.1 on 2021-02-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0012_auto_20210203_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mailing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_office', to='contact_page.address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mailing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_office', to='contact_page.address'),
        ),
    ]
