# Generated by Django 3.1.1 on 2021-02-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_page', '0013_auto_20210203_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
