# Generated by Django 3.1.1 on 2021-02-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_page', '0014_host_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logical_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='host',
        ),
        migrations.AddField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='contact_page.host'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='visitor',
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='contact_page.visitor'),
        ),
    ]
