# Generated by Django 3.1.1 on 2021-02-04 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0016_remove_visitor_mailing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_begin',
            field=models.TimeField(default=datetime.time(0, 25, 11, 629868)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2021, 2, 5)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_end',
            field=models.TimeField(default=datetime.time(0, 25, 11, 629868)),
        ),
    ]
