# Generated by Django 3.1.1 on 2021-02-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0017_auto_20210205_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_begin',
            field=models.TimeField(default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default='05/02/21'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_end',
            field=models.TimeField(default='00/00/00'),
        ),
    ]
