# Generated by Django 3.1.1 on 2021-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0018_auto_20210205_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default='06/02/21'),
        ),
    ]
