# Generated by Django 3.1.1 on 2021-02-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0019_auto_20210206_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='purpose',
            field=models.TextField(default='Unspecified'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default='07/02/21'),
        ),
    ]
