# Generated by Django 3.1.1 on 2021-02-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0020_auto_20210207_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='purpose',
            field=models.TextField(default='Unspecified', max_length=64),
        ),
    ]
