# Generated by Django 3.1.1 on 2021-02-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0022_auto_20210207_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='viewed_during_current_session',
            field=models.BooleanField(default=False),
        ),
    ]
