# Generated by Django 3.1.1 on 2021-02-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0023_meeting_viewed_during_current_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='viewed_during_current_session',
        ),
    ]
