# Generated by Django 3.1.1 on 2021-02-09 02:34

import contact_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0024_remove_meeting_viewed_during_current_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True, validators=[contact_page.models.phonenumber]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default='09/02/21'),
        ),
    ]
