# Generated by Django 3.1.1 on 2021-02-09 02:40

import contact_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0025_auto_20210209_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[contact_page.models.phonenumber]),
        ),
    ]
